---
helmCharts:
  - name: vault
    namespace: vault
    includeCRDs: false
    valuesFile: charts/vault/values.yaml
    version: 0.0.1
    releaseName: vault
    repo:  # we expand chart in folder
    valuesInline:
      vault:
        server:
          route:
            host: vault.apps.sno-in-sno.lab.apac-telco.net
          extraEnvironmentVars:
            VAULT_TLS_SERVER_NAME: vault.apps.sno-in-sno.lab.apac-telco.net
