---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
#  annotations:
#    unsupported.agent-install.openshift.io/assisted-service-configmap: my-assisted-service-config
#    unsupported.agent-install.openshift.io/assisted-image-service-skip-verify-tls: true
spec:
  databaseStorage:
    storageClassName: lvms-vgsno
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  filesystemStorage:
    storageClassName: lvms-vgsno
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  imageStorage:
    storageClassName: lvms-vgsno
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  osImages:
    - openshiftVersion: "4.17"
      version: "4.17.0"
      url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.17/4.17.0/rhcos-live.x86_64.iso"
      cpuArchitecture: "x86_64"