---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: mce
  namespace: mce
spec:
  baseDomain: sno.redhatlabs.dev
  clusterName: mce
  controlPlaneConfig:
    servingCertificates: {}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: mce
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "mce"
  pullSecretRef:
    name: pull-secret
