---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: mce
  namespace: mce
spec:
  applicationManager:
    enabled: false
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: Baremetal
    name: mce
    vendor: auto-detect
  clusterName: mce
  clusterNamespace: mce
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: false
---
kind: KlusterletConfig
apiVersion: config.open-cluster-management.io/v1alpha1
metadata:
  name: mce-import-klusterlet-config
  namespace: mce
spec:
  installMode:
    type: noOperator
    noOperator:
       postfix: mce-import
