---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: mce
  namespace: mce
spec:
  applicationManager:
#    argocdCluster: false
    enabled: false
  certPolicyController:
    enabled: true
  clusterLabels:
    name: mce
    cloud: Baremetal
    vendor: auto-detect
  clusterName: mce
  clusterNamespace: mce
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
