---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: engine
  namespace: multicluster-engine
spec:
  availabilityConfig: Basic
  overrides:
    components:
    - enabled: false
      name: local-cluster
    - enabled: true  ## FIXME - false for ACM > MCE pattern. but want UI to test.
      name: hypershift-local-hosting
