---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: acm-cluster
spec:
  description: "Policies for cluster configuration"
  policies:
    - acm-addon-ns
    - acm-addon-hypershift
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-acm-cluster
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-hub-openshift
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: acm-cluster
