---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mce-assisted-service
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-hub-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: mce-assisted-service-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: openshift-gitops
      source:
        repoURL: https://github.com/eformat/acm-sno-lab.git
        path: gitops/applications/assisted-service/overlay/mce
        plugin:
          name: argocd-novault-plugin-kustomize
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
