---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage-mce
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: mce-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-mce
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: storage-mce-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: vault
      source:
        repoURL: https://github.com/eformat/acm-sno-lab.git
        path: gitops/applications/storage/mce
        plugin:
          name: argocd-novault-plugin-kustomize
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
      syncOptions:
        - Validate=true
