---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: hcp-1
  namespace: hcp-1
  labels:
    cluster-name: hcp-1
spec:
  config:
    dns-resolver:
      config:
        server:
          - 192.168.130.1
    interfaces:
      - ipv4:
          address:
            - ip: 192.168.130.14
              prefix-length: 24
          dhcp: false
          enabled: true
        ipv6:
          enabled: false
        mac-address: '52:54:00:22:4d:4e'
        name: enp1s0
        state: up
        type: ethernet
    routes:
      config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.130.1
            next-hop-interface: enp1s0
            table-id: 254
  interfaces:
    - macAddress: '52:54:00:22:4d:4e'
      name: enp1s0
