---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: hcp-1
  namespace: clusters
spec:
  arch: amd64
  clusterName: hcp-1
  management:
    autoRepair: false
    upgradeType: InPlace
  nodeDrainTimeout: 0s
  platform:
    agent: {}
    type: Agent
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.16.17-multi
  replicas: 1
