---
apiVersion: v1
data:
  htpasswd: <HTPASSWORD>
kind: Secret
metadata:
  name: htpasswdidp-secret
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    hypershift.openshift.io/cluster: clusters/hcp-1
  creationTimestamp: null
  labels:
    hypershift.openshift.io/auto-created-for-infra: hcp-1
    hypershift.openshift.io/safe-to-delete-with-cluster: "true"
type: Opaque
